import type {
  PointsTableEntry,
  TournamentDetailData,
  TournamentMatch,
  TournamentPlayer,
  TournamentTeam,
} from "./tournament-detail.types";

function formatSlugToTitle(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function getMockTournamentDetail(slug: string): TournamentDetailData {
  const tournamentTitle =
    formatSlugToTitle(slug) || "Cricket Championship 2026";

  const defaultPlayersGroupA: TournamentPlayer[] = [
    { id: "p1", name: "Aarav Sharma", role: "Batsman", isCaptain: true },
    { id: "p2", name: "Kabir Patel", role: "All-Rounder", isViceCaptain: true },
    { id: "p3", name: "Rohan Varma", role: "Wicketkeeper" },
    { id: "p4", name: "Vikram Singh", role: "Bowler" },
    { id: "p5", name: "Arjun Reddy", role: "Bowler" },
    { id: "p6", name: "Devansh Nair", role: "Batsman" },
    { id: "p7", name: "Siddharth Rao", role: "All-Rounder" },
    { id: "p8", name: "Pranav Joshi", role: "Bowler" },
  ];

  const teams: TournamentTeam[] = [
    {
      id: "team-1",
      name: "Stallions Cricket Club",
      shortCode: "SCC",
      group: "Group A",
      captainName: "Aarav Sharma",
      coachName: "Mahesh Joshi",
      city: "Mumbai",
      playersCount: 15,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 3, lost: 1, points: 6, nrr: +1.285 },
    },
    {
      id: "team-2",
      name: "Royal Rhinos",
      shortCode: "RRH",
      group: "Group A",
      captainName: "Devansh Mehta",
      coachName: "Rahul Dravid Jr.",
      city: "Bangalore",
      playersCount: 14,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 3, lost: 1, points: 6, nrr: +0.892 },
    },
    {
      id: "team-3",
      name: "Thunderbolts XI",
      shortCode: "TBX",
      group: "Group A",
      captainName: "Kunal Ghosh",
      coachName: "Sunil Paul",
      city: "Kolkata",
      playersCount: 16,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 1, lost: 3, points: 2, nrr: -0.42 },
    },
    {
      id: "team-4",
      name: "Desert Falcons",
      shortCode: "DFL",
      group: "Group A",
      captainName: "Zaid Khan",
      coachName: "Imran Ali",
      city: "Ahmedabad",
      playersCount: 14,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 1, lost: 3, points: 2, nrr: -1.758 },
    },
    {
      id: "team-5",
      name: "Gladiators United",
      shortCode: "GLU",
      group: "Group B",
      captainName: "Hardik Verma",
      coachName: "Anil Sethi",
      city: "Delhi",
      playersCount: 15,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 4, lost: 0, points: 8, nrr: +2.115 },
    },
    {
      id: "team-6",
      name: "Coastal Strikers",
      shortCode: "CST",
      group: "Group B",
      captainName: "Naveen Raj",
      coachName: "Sanjay Kumar",
      city: "Chennai",
      playersCount: 15,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 2, lost: 2, points: 4, nrr: +0.21 },
    },
    {
      id: "team-7",
      name: "Northern Knights",
      shortCode: "NKN",
      group: "Group B",
      captainName: "Jaspreet Gill",
      coachName: "Balwinder Singh",
      city: "Chandigarh",
      playersCount: 14,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 1, lost: 3, points: 2, nrr: -0.91 },
    },
    {
      id: "team-8",
      name: "Deccan Hawks",
      shortCode: "DHK",
      group: "Group B",
      captainName: "Sai Teja",
      coachName: "Venkat Rao",
      city: "Hyderabad",
      playersCount: 15,
      players: defaultPlayersGroupA,
      stats: { matches: 4, won: 1, lost: 3, points: 2, nrr: -1.415 },
    },
  ];

  const matches: TournamentMatch[] = [
    {
      id: "m-live",
      matchNumber: 17,
      stage: "Group Stage",
      group: "Group A",
      teamA: {
        id: "team-1",
        name: "Stallions Cricket Club",
        shortCode: "SCC",
        score: { runs: 178, wickets: 6, overs: 20 },
      },
      teamB: {
        id: "team-2",
        name: "Royal Rhinos",
        shortCode: "RRH",
        score: { runs: 142, wickets: 4, overs: 16.2 },
      },
      status: "live",
      date: "Today",
      time: "03:30 PM",
      venue: "Wankhede Stadium, Ground A",
      currentOverDetails:
        "RRH need 37 runs in 22 balls | RR: 8.70 | Req: 10.09",
      tossInfo: "Royal Rhinos won the toss and elected to bowl first",
    },
    {
      id: "m-up-1",
      matchNumber: 18,
      stage: "Group Stage",
      group: "Group B",
      teamA: {
        id: "team-5",
        name: "Gladiators United",
        shortCode: "GLU",
      },
      teamB: {
        id: "team-6",
        name: "Coastal Strikers",
        shortCode: "CST",
      },
      status: "upcoming",
      date: "Tomorrow",
      time: "10:00 AM",
      venue: "Eden Gardens, Main Oval",
      tossInfo: "Toss scheduled at 09:30 AM",
    },
    {
      id: "m-up-2",
      matchNumber: 19,
      stage: "Group Stage",
      group: "Group A",
      teamA: {
        id: "team-3",
        name: "Thunderbolts XI",
        shortCode: "TBX",
      },
      teamB: {
        id: "team-4",
        name: "Desert Falcons",
        shortCode: "DFL",
      },
      status: "upcoming",
      date: "Tomorrow",
      time: "02:30 PM",
      venue: "Eden Gardens, Main Oval",
      tossInfo: "Toss scheduled at 02:00 PM",
    },
    {
      id: "m-up-3",
      matchNumber: 20,
      stage: "Group Stage",
      group: "Group B",
      teamA: {
        id: "team-7",
        name: "Northern Knights",
        shortCode: "NKN",
      },
      teamB: {
        id: "team-8",
        name: "Deccan Hawks",
        shortCode: "DHK",
      },
      status: "upcoming",
      date: "Sep 2, 2026",
      time: "01:30 PM",
      venue: "Chinnaswamy Stadium, Bangalore",
    },
    {
      id: "m-comp-1",
      matchNumber: 16,
      stage: "Group Stage",
      group: "Group B",
      teamA: {
        id: "team-5",
        name: "Gladiators United",
        shortCode: "GLU",
        score: { runs: 204, wickets: 3, overs: 20 },
      },
      teamB: {
        id: "team-7",
        name: "Northern Knights",
        shortCode: "NKN",
        score: { runs: 148, wickets: 9, overs: 20 },
      },
      status: "completed",
      date: "Yesterday",
      time: "02:30 PM",
      venue: "Feroz Shah Kotla, Ground 1",
      resultSummary: "Gladiators United won by 56 runs",
      tossInfo: "Gladiators won toss and elected to bat first",
    },
    {
      id: "m-comp-2",
      matchNumber: 15,
      stage: "Group Stage",
      group: "Group A",
      teamA: {
        id: "team-1",
        name: "Stallions Cricket Club",
        shortCode: "SCC",
        score: { runs: 165, wickets: 7, overs: 20 },
      },
      teamB: {
        id: "team-3",
        name: "Thunderbolts XI",
        shortCode: "TBX",
        score: { runs: 151, wickets: 8, overs: 20 },
      },
      status: "completed",
      date: "Aug 27, 2026",
      time: "10:00 AM",
      venue: "Wankhede Stadium, Ground A",
      resultSummary: "Stallions Cricket Club won by 14 runs",
      tossInfo: "Thunderbolts XI elected to bowl first",
    },
    {
      id: "m-comp-3",
      matchNumber: 14,
      stage: "Group Stage",
      group: "Group B",
      teamA: {
        id: "team-6",
        name: "Coastal Strikers",
        shortCode: "CST",
        score: { runs: 182, wickets: 5, overs: 20 },
      },
      teamB: {
        id: "team-8",
        name: "Deccan Hawks",
        shortCode: "DHK",
        score: { runs: 179, wickets: 7, overs: 20 },
      },
      status: "completed",
      date: "Aug 26, 2026",
      time: "02:30 PM",
      venue: "MA Chidambaram Stadium",
      resultSummary: "Coastal Strikers won by 3 runs",
      tossInfo: "Coastal Strikers elected to bat first",
    },
  ];

  const pointsTable: PointsTableEntry[] = [
    // Group A
    {
      rank: 1,
      teamId: "team-1",
      teamName: "Stallions Cricket Club",
      shortCode: "SCC",
      group: "Group A",
      played: 4,
      won: 3,
      lost: 1,
      tied: 0,
      noResult: 0,
      netRunRate: 1.285,
      points: 6,
      form: ["W", "W", "L", "W"],
      qualified: true,
    },
    {
      rank: 2,
      teamId: "team-2",
      teamName: "Royal Rhinos",
      shortCode: "RRH",
      group: "Group A",
      played: 4,
      won: 3,
      lost: 1,
      tied: 0,
      noResult: 0,
      netRunRate: 0.892,
      points: 6,
      form: ["W", "L", "W", "W"],
      qualified: true,
    },
    {
      rank: 3,
      teamId: "team-3",
      teamName: "Thunderbolts XI",
      shortCode: "TBX",
      group: "Group A",
      played: 4,
      won: 1,
      lost: 3,
      tied: 0,
      noResult: 0,
      netRunRate: -0.42,
      points: 2,
      form: ["L", "L", "W", "L"],
    },
    {
      rank: 4,
      teamId: "team-4",
      teamName: "Desert Falcons",
      shortCode: "DFL",
      group: "Group A",
      played: 4,
      won: 1,
      lost: 3,
      tied: 0,
      noResult: 0,
      netRunRate: -1.758,
      points: 2,
      form: ["L", "W", "L", "L"],
    },
    // Group B
    {
      rank: 1,
      teamId: "team-5",
      teamName: "Gladiators United",
      shortCode: "GLU",
      group: "Group B",
      played: 4,
      won: 4,
      lost: 0,
      tied: 0,
      noResult: 0,
      netRunRate: 2.115,
      points: 8,
      form: ["W", "W", "W", "W"],
      qualified: true,
    },
    {
      rank: 2,
      teamId: "team-6",
      teamName: "Coastal Strikers",
      shortCode: "CST",
      group: "Group B",
      played: 4,
      won: 2,
      lost: 2,
      tied: 0,
      noResult: 0,
      netRunRate: 0.21,
      points: 4,
      form: ["L", "W", "L", "W"],
      qualified: true,
    },
    {
      rank: 3,
      teamId: "team-7",
      teamName: "Northern Knights",
      shortCode: "NKN",
      group: "Group B",
      played: 4,
      won: 1,
      lost: 3,
      tied: 0,
      noResult: 0,
      netRunRate: -0.91,
      points: 2,
      form: ["W", "L", "L", "L"],
    },
    {
      rank: 4,
      teamId: "team-8",
      teamName: "Deccan Hawks",
      shortCode: "DHK",
      group: "Group B",
      played: 4,
      won: 1,
      lost: 3,
      tied: 0,
      noResult: 0,
      netRunRate: -1.415,
      points: 2,
      form: ["L", "L", "L", "W"],
    },
  ];

  return {
    name: tournamentTitle,
    slug,
    status: "Active",
    formatBadge: "T20 Championship",
    location: "Mumbai & Bangalore, India",
    startDate: "Aug 20, 2026",
    endDate: "Sep 15, 2026",
    prizePool: "₹500,000",
    bannerGradient: "from-zinc-900 via-zinc-800 to-zinc-950",
    summaryStats: {
      totalTeams: teams.length,
      totalMatches: 24,
      completedMatches: 16,
      totalRuns: 5420,
      totalWickets: 218,
      topBatter: {
        name: "Aarav Sharma",
        team: "Stallions",
        runs: 284,
        strikeRate: 154.2,
      },
      topBowler: {
        name: "Vikram Singh",
        team: "Stallions",
        wickets: 12,
        economy: 6.45,
      },
    },
    teams,
    matches,
    pointsTable,
    milestones: [
      {
        id: "m1",
        title: "Team Registrations & Rosters Finalized",
        date: "Aug 10, 2026",
        status: "completed",
        description: "8 teams officially registered and squads locked.",
      },
      {
        id: "m2",
        title: "Group Stage Round-Robin",
        date: "Aug 20 - Sep 06, 2026",
        status: "active",
        description: "16 of 20 group matches completed.",
      },
      {
        id: "m3",
        title: "Semi-Finals",
        date: "Sep 10, 2026",
        status: "upcoming",
        description: "Top 2 teams from Group A & B battle for the finals spot.",
      },
      {
        id: "m4",
        title: "Grand Championship Final",
        date: "Sep 15, 2026",
        status: "upcoming",
        description: "Held at Wankhede Stadium with live broadcast & trophy.",
      },
    ],
    settings: {
      format: "T20",
      oversPerInnings: 20,
      ballsPerOver: 6,
      powerplayOvers: 6,
      maxOversPerBowler: 4,
      ballType: "Leather (White)",
      pitchType: "Natural Turf",
      superOverEnabled: true,
      dlsMethodEnabled: true,
      widePenalty: 1,
      noBallPenalty: 1,
      freeHitOnNoBall: true,
      leadUmpire: "Suresh Shastri (ICC Elite Panel)",
      officialScorer: "Amitabh Banerjee",
    },
  };
}
